# Generated by Django 4.1.7 on 2023-03-12 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cozy_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_customer", models.CharField(max_length=100)),
                ("nama_customer", models.CharField(max_length=100)),
                ("no_telp", models.CharField(max_length=15, null=True)),
                ("email", models.CharField(max_length=100, null=True)),
                ("alamat", models.TextField(null=True)),
                ("nama_perusahaan", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Kategori_Material",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_kategori_material", models.CharField(max_length=100)),
                ("nama_kategori", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_material", models.CharField(max_length=100)),
                ("nama_material", models.CharField(max_length=100)),
                ("harga", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_kategori_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cozy_app.kategori_material",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_project", models.CharField(max_length=100)),
                ("nama_project", models.CharField(max_length=100)),
                ("jumlah_volumn", models.CharField(max_length=100)),
                ("estimasi_pengerjaan", models.CharField(max_length=100)),
                ("kategori_project", models.CharField(max_length=50)),
                ("total_cost", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cozy_app.customer",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stok_Gudang",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_stok_gudang", models.CharField(max_length=100)),
                ("stok", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cozy_app.material",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stok_Out",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_stok_out", models.CharField(max_length=100)),
                ("stok_out", models.BigIntegerField()),
                ("katerangan", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cozy_app.material",
                    ),
                ),
                (
                    "id_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cozy_app.project",
                    ),
                ),
                (
                    "id_stok_gudang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cozy_app.stok_gudang",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stok_In",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_stok_in", models.CharField(max_length=100)),
                ("stok_in", models.BigIntegerField()),
                ("katerangan", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cozy_app.material",
                    ),
                ),
                (
                    "id_stok_gudang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cozy_app.stok_gudang",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Progress_Project",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_progress_project", models.CharField(max_length=100)),
                ("nama_progress", models.CharField(max_length=100)),
                ("desc", models.TextField(null=True)),
                ("percentage", models.IntegerField()),
                ("status", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cozy_app.project",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cost_Project",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_cost_project", models.CharField(max_length=100)),
                ("cost_design", models.BigIntegerField()),
                ("cost_operasional", models.BigIntegerField()),
                ("cost_produksi", models.BigIntegerField()),
                ("cost_bahan", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cozy_app.project",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
