# Generated by Django 4.1.7 on 2023-03-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cozy_app", "0003_modified_stok"),
    ]

    operations = [
        migrations.AddField(
            model_name="stok_gudang",
            name="last_stok",
            field=models.BigIntegerField(null=True),
        ),
    ]
