# Generated by Django 4.1.7 on 2023-03-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cozy_app", "0004_stok_gudang_last_stok"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cost_project",
            name="cost_bahan",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="cost_project",
            name="cost_design",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="cost_project",
            name="cost_operasional",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="cost_project",
            name="cost_produksi",
            field=models.BigIntegerField(null=True),
        ),
    ]
