# Generated by Django 4.1.7 on 2023-03-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cozy_app", "0005_alter_cost_project_cost_bahan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="start_date",
            field=models.DateField(null=True),
        ),
    ]
