# Generated by Django 4.1.7 on 2023-03-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cozy_app", "0006_project_end_date_project_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
