# Generated by Django 4.1.7 on 2023-03-20 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cozy_app", "0007_project_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pekerjaan_Lain",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_pekerjaan_lain", models.CharField(max_length=100)),
                ("nama_pekerjaan", models.CharField(max_length=100)),
                ("desc", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cozy_app.project",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
