# Generated by Django 4.1.7 on 2023-03-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cozy_app", "0008_pekerjaan_lain"),
    ]

    operations = [
        migrations.AddField(
            model_name="cost_project",
            name="cost_lain",
            field=models.BigIntegerField(null=True),
        ),
    ]
