# Generated by Django 4.1.7 on 2023-03-23 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cozy_app", "0010_project_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cost_project",
            name="id_project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="cozy_app.project"
            ),
        ),
        migrations.AlterField(
            model_name="cost_project",
            name="id_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="id_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="id_kategori_material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="cozy_app.kategori_material",
            ),
        ),
        migrations.AlterField(
            model_name="modified_stok",
            name="id_material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="cozy_app.material"
            ),
        ),
        migrations.AlterField(
            model_name="modified_stok",
            name="id_stok_gudang",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="cozy_app.stok_gudang",
            ),
        ),
        migrations.AlterField(
            model_name="pekerjaan_lain",
            name="id_project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="cozy_app.project"
            ),
        ),
        migrations.AlterField(
            model_name="pekerjaan_lain",
            name="id_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="progress_project",
            name="id_project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="cozy_app.project"
            ),
        ),
        migrations.AlterField(
            model_name="progress_project",
            name="id_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="id_customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="cozy_app.customer"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="id_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="stok_gudang",
            name="id_material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="cozy_app.material"
            ),
        ),
        migrations.AlterField(
            model_name="stok_in",
            name="id_material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="cozy_app.material"
            ),
        ),
        migrations.AlterField(
            model_name="stok_in",
            name="id_stok_gudang",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="cozy_app.stok_gudang",
            ),
        ),
        migrations.AlterField(
            model_name="stok_in",
            name="id_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="stok_out",
            name="id_material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="cozy_app.material"
            ),
        ),
        migrations.AlterField(
            model_name="stok_out",
            name="id_project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="cozy_app.project"
            ),
        ),
        migrations.AlterField(
            model_name="stok_out",
            name="id_stok_gudang",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="cozy_app.stok_gudang",
            ),
        ),
        migrations.AlterField(
            model_name="stok_out",
            name="id_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
