# Generated by Django 4.1.7 on 2023-03-23 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cozy_app", "0011_alter_cost_project_id_project_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cost_project",
            name="id_project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cozy_app.project"
            ),
        ),
        migrations.AlterField(
            model_name="progress_project",
            name="id_project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cozy_app.project"
            ),
        ),
    ]
