# Generated by Django 4.1.7 on 2023-03-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cozy_app", "0012_alter_cost_project_id_project_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progress_project",
            name="percentage",
            field=models.IntegerField(null=True),
        ),
    ]
