# Generated by Django 4.1.7 on 2023-03-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cozy_app", "0013_alter_progress_project_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="pekerjaan_lain",
            name="harga",
            field=models.BigIntegerField(null=True),
        ),
    ]
