# Generated by Django 4.1.7 on 2023-04-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cozy_app", "0014_pekerjaan_lain_harga"),
    ]

    operations = [
        migrations.AddField(
            model_name="modified_stok",
            name="last_stok",
            field=models.BigIntegerField(null=True),
        ),
    ]
