# Generated by Django 4.1.7 on 2023-04-03 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cozy_app", "0015_modified_stok_last_stok"),
    ]

    operations = [
        migrations.AddField(
            model_name="modified_stok",
            name="id_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="modified_stok",
            name="stok_in",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="modified_stok",
            name="stok_out",
            field=models.BigIntegerField(null=True),
        ),
    ]
