# Generated by Django 4.1.7 on 2023-06-04 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cozy_app', '0016_modified_stok_id_user_modified_stok_stok_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_user_detail', models.CharField(max_length=100)),
                ('img', models.ImageField(default='profile.png', upload_to='img_user/')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
