# Generated by Django 4.1.7 on 2023-06-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozy_app', '0017_user_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user_detail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
