# Generated by Django 4.1.7 on 2023-06-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozy_app', '0018_user_detail_created_at_user_detail_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress_project',
            name='foto',
            field=models.ImageField(null=True, upload_to='progress/'),
        ),
    ]
