# Generated by Django 4.1.7 on 2023-06-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozy_app', '0021_alter_progress_project_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress_project',
            name='foto',
            field=models.FileField(default='', upload_to='progress/'),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='img',
            field=models.FileField(default='profile.png', upload_to='img_user/'),
        ),
    ]
