# Generated by Django 4.1.7 on 2023-06-09 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cozy_app', '0022_alter_cost_project_id_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modified_stok',
            name='id_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cozy_app.project'),
        ),
        migrations.AlterField(
            model_name='stok_gudang',
            name='id_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cozy_app.material'),
        ),
    ]
