# Generated by Django 4.1.7 on 2023-06-06 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cozy_app', '0022_alter_cost_project_id_project_and_more'),
        ('cozy_app', '0022_alter_progress_project_foto_alter_user_detail_img'),
    ]

    operations = [
    ]
