# Generated by Django 4.1.7 on 2023-06-09 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cozy_app', '0024_historicalstok_out_historicalstok_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stok_in',
            name='id_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cozy_app.material'),
        ),
        migrations.AlterField(
            model_name='stok_in',
            name='id_stok_gudang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cozy_app.stok_gudang'),
        ),
        migrations.AlterField(
            model_name='stok_out',
            name='id_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cozy_app.material'),
        ),
        migrations.AlterField(
            model_name='stok_out',
            name='id_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cozy_app.project'),
        ),
        migrations.AlterField(
            model_name='stok_out',
            name='id_stok_gudang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cozy_app.stok_gudang'),
        ),
    ]
