# Generated by Django 4.1.7 on 2023-06-09 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cozy_app', '0025_alter_stok_in_id_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cozy_app.customer'),
        ),
    ]
