# Generated by Django 4.1.7 on 2023-08-12 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cozy_app', '0023_merge_20230606_1840'),
        ('cozy_app', '0028_alter_stok_gudang_id_material'),
    ]

    operations = [
    ]
