# Generated by Django 4.1.7 on 2023-08-26 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('cozy_app', '0029_merge_20230812_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toko_Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_toko_material', models.CharField(max_length=100)),
                ('nama_toko', models.CharField(max_length=100)),
                ('keterangan', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_stok_gudang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cozy_app.stok_gudang')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalToko_Material',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('id_toko_material', models.CharField(max_length=100)),
                ('nama_toko', models.CharField(max_length=100)),
                ('keterangan', models.TextField(null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id_stok_gudang', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cozy_app.stok_gudang')),
            ],
            options={
                'verbose_name': 'historical toko_ material',
                'verbose_name_plural': 'historical toko_ materials',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
