# Generated by Django 4.1.7 on 2023-08-26 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cozy_app', '0030_toko_material_historicaltoko_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltoko_material',
            name='id_stok_gudang',
        ),
        migrations.RemoveField(
            model_name='toko_material',
            name='id_stok_gudang',
        ),
        migrations.AddField(
            model_name='historicaltoko_material',
            name='id_material',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cozy_app.material'),
        ),
        migrations.AddField(
            model_name='toko_material',
            name='id_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cozy_app.material'),
        ),
    ]
