# Generated by Django 4.1.7 on 2023-08-26 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cozy_app', '0031_remove_historicaltoko_material_id_stok_gudang_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltoko_material',
            name='id_material',
        ),
        migrations.RemoveField(
            model_name='toko_material',
            name='id_material',
        ),
        migrations.AddField(
            model_name='historicaltoko_material',
            name='id_stok_in',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cozy_app.stok_in'),
        ),
        migrations.AddField(
            model_name='toko_material',
            name='id_stok_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cozy_app.stok_in'),
        ),
    ]
