# Generated by Django 4.1.7 on 2023-08-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozy_app', '0032_remove_historicaltoko_material_id_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstok_in',
            name='nama_toko',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stok_in',
            name='nama_toko',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
