# Generated by Django 4.1.7 on 2023-08-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozy_app', '0033_historicalstok_in_nama_toko_stok_in_nama_toko'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstok_in',
            name='nama_toko',
        ),
        migrations.RemoveField(
            model_name='stok_in',
            name='nama_toko',
        ),
        migrations.AddField(
            model_name='historicalmodified_stok',
            name='nama_toko',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modified_stok',
            name='nama_toko',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
