# Generated by Django 4.1.7 on 2023-08-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozy_app', '0034_remove_historicalstok_in_nama_toko_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_alat', models.CharField(max_length=100)),
                ('nama_alat', models.CharField(max_length=100)),
                ('harga_alat', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
