# Generated by Django 4.1.7 on 2023-08-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozy_app', '0035_alat'),
    ]

    operations = [
        migrations.AddField(
            model_name='alat',
            name='qty',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
