# Generated by Django 4.1.7 on 2023-08-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozy_app', '0036_alat_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='alat',
            name='total_harga',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
