# Generated by Django 4.1.7 on 2023-08-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozy_app', '0038_remove_alat_total_harga'),
    ]

    operations = [
        migrations.AddField(
            model_name='alat',
            name='total_harga',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
