# Generated by Django 4.1.7 on 2023-08-29 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cozy_app', '0039_alat_total_harga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori_Unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_kategori_unit', models.CharField(max_length=100)),
                ('nama_kategori', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rincian_Unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_rincian_unit', models.CharField(max_length=100)),
                ('nama_unit', models.CharField(max_length=100)),
                ('dimensi', models.CharField(max_length=100)),
                ('desc', models.TextField(null=True)),
                ('cost_produksi', models.CharField(max_length=100, null=True)),
                ('cost_operasional', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id_kategori_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cozy_app.kategori_unit')),
                ('id_project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cozy_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='Pekerjaan_Lain_Unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_pekerjaan_lain_unit', models.CharField(max_length=100)),
                ('judul_pekerjaan', models.CharField(max_length=100)),
                ('harga', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id_rincian_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cozy_app.rincian_unit')),
            ],
        ),
        migrations.CreateModel(
            name='Kebutuhan_Material_Unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_kebutuhan_material_unit', models.CharField(max_length=100)),
                ('nama_bahan', models.CharField(max_length=100)),
                ('harga', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('total', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id_rincian_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cozy_app.rincian_unit')),
            ],
        ),
        migrations.CreateModel(
            name='Image_Unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_image_unit', models.CharField(max_length=100)),
                ('url_image', models.FileField(upload_to='image_unit/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id_rincian_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cozy_app.rincian_unit')),
            ],
        ),
    ]
