# Generated by Django 4.1.7 on 2023-08-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozy_app', '0040_kategori_unit_rincian_unit_pekerjaan_lain_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rincian_unit',
            name='cost_operasional',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rincian_unit',
            name='cost_produksi',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
    ]
