# Generated by Django 4.1.7 on 2023-09-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozy_app', '0041_alter_rincian_unit_cost_operasional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rincian_unit',
            name='cover',
            field=models.TextField(null=True),
        ),
    ]
