from .view.kategori_material import KategoriMaterialView
from .view.material import MaterialView
from .view.stok import *
from .view.customer import *
from .view.project import *
from .view.cost_project import *
from .view.progress_project import *
from .view.user import *
from .view.pekerjaan_lain import *
from .view.analisis import *